[build]
  functions = "functions"

[[redirects]]
  from = "/socket.io/*"
  to = "/functions/function"
  status = 200
  force = true

[dev]
  functions = "functions"
  command = "npm run dev"
  port = 3000
